In [24]:
%matplotlib widget
edges = [
    (0,1),
    (0,2),
    (1,3),
    (1,4),
    (2,3),
    (3,4)
]
import scipy.linalg as la
import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt
X = cp.Variable((5,5), symmetric=True)

constraints = [X >> 0]
constraints += [
    X[i, i] == 1 for i in range(5)
]

objective = sum( .5*(1-X[i, j]) for (i, j) in edges)
print(f'objective = {objective}')
prob = cp.Problem(cp.Maximize(objective), constraints)
print(prob.solve())

evals, evects = np.linalg.eigh(X.value)
sdp_vectors = evects.T[evals > float(1.0E-6)].T
print(sdp_vectors)

objective = 0.5 @ (1.0 + -var3364[0, 1]) + 0.5 @ (1.0 + -var3364[0, 2]) + 0.5 @ (1.0 + -var3364[1, 3]) + 0.5 @ (1.0 + -var3364[1, 4]) + 0.5 @ (1.0 + -var3364[2, 3]) + 0.5 @ (1.0 + -var3364[3, 4])
5.185492438628354
[[-9.06549825e-02  1.09505058e-01 -5.15827518e-01]
 [-6.28911893e-01 -3.21683703e-01  4.83654806e-01]
 [-9.06549824e-02  1.09505058e-01  5.15827518e-01]
 [-6.28911893e-01 -3.21683703e-01 -4.83654806e-01]
 [-4.38751650e-01  8.76958650e-01  1.04083409e-15]]
